Try cmd + activate.bat

diff --git a/.github/workflows/build_cmake.yml b/.github/workflows/build_cmake.yml
--- a/.github/workflows/build_cmake.yml
+++ b/.github/workflows/build_cmake.yml
@@ -209,27 +209,6 @@ jobs:
         restore-keys: |
           ${{ matrix.config.name }}-ccache-${{ env.CACHE_PARTITION }}-
 
-    # For Conan
-    - uses: actions/setup-python@v1
-      if: runner.os == 'Windows'
-      with:
-        python-version: '3.7'
-
-    - name: Install conan
-      if: runner.os == 'Windows'
-      run: |
-        pip3 install conan
-        mkdir build
-        conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
-        conan remote add qtproject https://api.bintray.com/conan/qtproject/conan
-        conan install --no-imports --install-folder build Tools/qt/conanfile.py
-
-    - name: Test
-      shell: bash --noprofile --norc -eo pipefail -x {0}
-      run: |
-        cat build/activate.bat
-        cat build/environment.bat.env
-
     - name: Configure
       if: runner.os != 'Windows' || matrix.config.environment_script == ''
       shell: bash --noprofile --norc -eo pipefail -x {0}
@@ -257,65 +236,89 @@ jobs:
             -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
             $cmake_extra_args
 
-#    - name: Configure
-#      if: runner.os == 'Windows' && matrix.config.environment_script != ''
-#      shell: cmd
-#      run: |
-#        "${{ matrix.config.environment_script }}" && ^
-#        set PATH=%GITHUB_WORKSPACE%;%$PATH% && ^
-#        set CC=${{ matrix.config.cc }} && ^
-#        set CXX=${{ matrix.config.cxx }} && ^
-#        ${{ steps.cmake_and_ninja.outputs.cmake_dir }}/cmake ^
-#            -H. ^
-#            -Bbuild ^
-#            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} ^
-#            -GNinja ^
-#            -DCMAKE_C_COMPILER_LAUNCHER=ccache ^
-#            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache ^
-#            -DRUN_CONAN=ON
+    # For Conan
+    - uses: actions/setup-python@v1
+      if: runner.os == 'Windows'
+      with:
+        python-version: '3.7'
+
+    - name: Install conan
+      if: runner.os == 'Windows'
+      run: |
+        pip3 install conan
+        mkdir build
+        conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
+        conan remote add qtproject https://api.bintray.com/conan/qtproject/conan
+        conan install --no-imports --install-folder build Tools/qt/conanfile.py
+
+    - name: Test
+      shell: bash --noprofile --norc -eo pipefail -x {0}
+      run: |
+        cat build/activate.bat
+        cat build/environment.bat.env
 
     - name: Configure
       if: runner.os == 'Windows' && matrix.config.environment_script != ''
-      shell: cmake -P {0}
+      env:
+        CC: ${{ matrix.config.cc }}
+        CXX: ${{ matrix.config.cxx }}
+      shell: cmd
       run: |
-        set(ENV{CC} ${{ matrix.config.cc }})
-        set(ENV{CXX} ${{ matrix.config.cxx }})
-
-        if ("${{ runner.os }}" STREQUAL "Windows" AND NOT "x${{ matrix.config.environment_script }}" STREQUAL "x")
-          execute_process(
-            COMMAND "${{ matrix.config.environment_script }}" && set
-            OUTPUT_FILE environment_script_output.txt
-          )
-          file(STRINGS environment_script_output.txt output_lines)
-          foreach(line IN LISTS output_lines)
-            if (line MATCHES "^([a-zA-Z0-9_-]+)=(.*)$")
-              set(ENV{${CMAKE_MATCH_1}} "${CMAKE_MATCH_2}")
-            endif()
-          endforeach()
-        endif()
-
-        set(path_separator ":")
-        if ("${{ runner.os }}" STREQUAL "Windows")
-          set(path_separator ";")
-        endif()
-        set(ENV{PATH} "$ENV{GITHUB_WORKSPACE}${path_separator}$ENV{PATH}")
-
-        execute_process(
-          COMMAND ${{ steps.cmake_and_ninja.outputs.cmake_dir }}/cmake
-            -H.
-            -Bbuild
-            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
-            -GNinja
-            -DCMAKE_C_COMPILER_LAUNCHER=ccache
-            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
+        call "${{ matrix.config.environment_script }}"
+        call build/activate.bat
+        set PATH=%GITHUB_WORKSPACE%;%$PATH%
+        ${{ steps.cmake_and_ninja.outputs.cmake_dir }}/cmake ^
+            -H. ^
+            -Bbuild ^
+            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} ^
+            -GNinja ^
+            -DCMAKE_C_COMPILER_LAUNCHER=ccache ^
+            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache ^
             -DQt5_DIR=${{ steps.qt.outputs.qt_dir }}/lib/cmake/Qt5
             -DQT_CONAN_DIR=build
-          RESULT_VARIABLE result
-          COMMAND_ECHO STDOUT
-        )
-        if (NOT result EQUAL 0)
-          message(FATAL_ERROR "Bad exit status")
-        endif()
+
+#    - name: Configure
+#      if: runner.os == 'Windows' && matrix.config.environment_script != ''
+#      shell: cmake -P {0}
+#      run: |
+#        set(ENV{CC} ${{ matrix.config.cc }})
+#        set(ENV{CXX} ${{ matrix.config.cxx }})
+#
+#        if ("${{ runner.os }}" STREQUAL "Windows" AND NOT "x${{ matrix.config.environment_script }}" STREQUAL "x")
+#          execute_process(
+#            COMMAND "${{ matrix.config.environment_script }}" && set
+#            OUTPUT_FILE environment_script_output.txt
+#          )
+#          file(STRINGS environment_script_output.txt output_lines)
+#          foreach(line IN LISTS output_lines)
+#            if (line MATCHES "^([a-zA-Z0-9_-]+)=(.*)$")
+#              set(ENV{${CMAKE_MATCH_1}} "${CMAKE_MATCH_2}")
+#            endif()
+#          endforeach()
+#        endif()
+#
+#        set(path_separator ":")
+#        if ("${{ runner.os }}" STREQUAL "Windows")
+#          set(path_separator ";")
+#        endif()
+#        set(ENV{PATH} "$ENV{GITHUB_WORKSPACE}${path_separator}$ENV{PATH}")
+#
+#        execute_process(
+#          COMMAND ${{ steps.cmake_and_ninja.outputs.cmake_dir }}/cmake
+#            -H.
+#            -Bbuild
+#            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
+#            -GNinja
+#            -DCMAKE_C_COMPILER_LAUNCHER=ccache
+#            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
+#            -DQt5_DIR=${{ steps.qt.outputs.qt_dir }}/lib/cmake/Qt5
+#            -DQT_CONAN_DIR=build
+#          RESULT_VARIABLE result
+#          COMMAND_ECHO STDOUT
+#        )
+#        if (NOT result EQUAL 0)
+#          message(FATAL_ERROR "Bad exit status")
+#        endif()
 
 
 #    - uses: actions/upload-artifact@v1
